version: 2.1

# Define the jobs we want to run for this project

jobs:
  build:
    docker:
      - image: circleci/node@4.5.1
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm install
      - run: npm test
  test:
    docker:
      - image: circleci/node@4.5.1
    steps:
      - checkout
      - run: echo "build project"
      - run: npm install
      - run: npm run build

# Orchestrate our job run sequence
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test