export const FLance = {
  name: "JPHOBBYEXPRESS (Freelance Project)",
  description:
    "A commercial online shopping site serving customers from United Kingdom and Asia for Japanese anime goods.",
  techs: [
    "React & Redux",
    "NextJS",
    "TypeScript",
    "Server-Sided Rendering",
    "Serverless Functions",
    "TailwindCSS",
    "AWS RDS PostgreSQL (Database)",
    "Agile (accerlerate development)",
    "CI/CD (Long-Term Maintenance)",
    "Prisma (ORM for connection pooling)",
    "Jest & Enzyme (TDD)",
    "React Router & Next Link",
    "I18n (Locales)",
    "Framer Motion (Animation)",
    "JWT & Bcrypt (Encryption)",
    "And more...",
  ],
  functions: [
    "Receive products from database through Server-Sided Rendering",
    "Handle adding, deleting & updating shopping cart (Redux store)",
    "Create order with Serverless Functions & Send it to AWS RDS PostgreSQL",
    "User passwords & information encryted by JWT & Bcrypt",
    "Order Tracking for each orders",
    "Provide browsing with both Chinese & English Languages",
  ],
  id: "0000",
};

export const blog = {
  name: "NextJS Personal Blog",
  description: "A Static Generation Site using NextJS",
  techs: [
    "NextJS",
    "ReactJS",
    "MongoDB",
    "Jest & Enzyme",
    "TailwindCSS",
    "fs, marked & gray-matter",
  ],
  functions: [
    "Flexibility for using SSG & SSR",
    "Superfast speed for SSG pages",
    "SEO-efficient for SSR pages",
    "Read .md files from post folder",
    "Convert .md files into httpStrings",
    "Store visitor's comments",
  ],
  id: "0001",
  link: [
    "https://github.com/theo923/next-ssg-personal-blog",
    "https://theo923.com/",
  ],
  linkdescription: [
    "Click to View the Repository",
    "Click to View the Deployment Site",
  ],
  linkicon: ["Github", "Window"],
};

export const Netfake = {
  name: "Netfake",
  description: "A netflix clone",
  techs: [
    "ReactJS",
    "TypeScript",
    "TailwindCSS",
    "AXIOS",
    "Jest & Enzyme",
    "movie-trailer",
    "youtube-search",
    "The Movie Database API",
    "YouTube API v3",
  ],
  functions: [
    "Get series/movie from The Movie Database API",
    "Clicked on the poster, the information of item will be shown",
    "movie-trailer for initial search on trailer",
    "search-youtube for backup plan on searching trailer",
  ],
  id: "0002",
  link: ["https://github.com/theo923/netfake", "https://netfake.vercel.app/"],
  linkdescription: [
    "Click to View the Repository",
    "Click to View the Deployment Site",
  ],
  linkicon: ["Github", "Window"],
};

export const shop = {
  name: "React Shopping Mall & Docker Image",
  description: "A Online Shopping Mall for online shopping and order tracking",
  techs: [
    "ReactJS",
    "TypeScript",
    "ExpressJS",
    "PostgreSQL",
    "Docker",
    "Unraid OS",
    "daisyui",
    "knex",
    "helmet",
    "bcrypt-nodejs",
  ],
  functions: [
    "Frontend is connecting to Server and Database",
    "Heroku Deployment for all (Client, Server, Database)",
    "Register & Login function",
    "Allowing to add item into Shopping Cart",
    "Applied bcrpyt for encrytion",
    "Receiving user's order by converting JSON to string",
    "Send data to database from Express & knex",
    "Fetching user's order by converting string into JSON",
    "Setup Image in Docker & Unraid for local environment",
  ],
  id: "0003",
  link: [
    "https://github.com/theo923/React_Shopping_Mall",
    "https://github.com/theo923/React_Shopping_Mall_API",
    "https://github.com/theo923/react-shopping-mall-ts-server-docker",
    "https://react-shopping-mall.netlify.app/",
  ],
  linkdescription: [
    "Click to View Client's Repository",
    "Click to View Server's Repository",
    "Click to View Docker's Repository",
    "Click to View the Deployment Site",
  ],
  linkicon: ["Github", "Github", "Github", "Window"],
};
